blank_issues_enabled: false
contact_links:
  - name: "Check if existing issues already exist"
    url: https://github.com/zSemper/JEI-Integration-MCreator-Plugin/issues
    about: The place for issues
  - name: "JEI Integration's forum page"
    url: https://mcreator.net/plugin/119445/jei-integration
    about: Alternative place to report bugs or feature requests, also place for support questions